version: '2'
services:
  bioportal-4store:
    build: ./bioportal-4store
    container_name: bioportal-4store
    ports: 
      - "9000:9000"
    volumes: 
      - ./data/4store/:/var/lib/4store
  bioportal-mgrep:
    build: ./bioportal-mgrep
    container_name: bioportal-mgrep
    ports: 
      - "55555:55555"
    volumes:
      - ./data/mgrep/:/opt/mgrep/dictionary
  bioportal-solr:
    build: ./bioportal-solr
    container_name: bioportal-solr
    ports: 
      - "8983"
  redis-annotator:
    image: redis:3.0.7-alpine
    ports: 
      - "6379"
    volumes:
      - ./data/redis/annotator/:/data
  redis-http:
    image: redis:3.0.7-alpine
    ports: 
      - "6379"
    volumes:
      - ./data/redis/http/:/data
  redis-goo:
    image: redis:3.0.7-alpine
    ports: 
      - "6379"
    volumes:
      - ./data/redis/goo:/data
  bioportal-api:
    build: ./bioportal-api/
    container_name: bioportal-api
    volumes:
      - ./data/bioportal:/srv/bioportal/
      - ./data/ncbo/ncbo_cron/logs:/srv/ncbo/ncbo_cron/logs/
      - ./data/mgrep/:/srv/mgrep/dictionary
    ports:
      - "8080:8080"
      - "2222:22"
    depends_on:
      - redis-http
      - redis-goo
      - redis-annotator
      - bioportal-mgrep
      - bioportal-solr
      - bioportal-4store
    links:
      - redis-http
      - redis-goo
      - redis-annotator
      - bioportal-mgrep
      - bioportal-solr
      - bioportal-4store
  bioportal-annotator-proxy:
    build: ./bioportal-annotator-proxy/
    container_name: bioportal-annotator-proxy
    ports:
      - "8081:8081"
    depends_on:
      - bioportal-api
    links:
      - bioportal-api
