version: '2'
services:
  bioportal-4store:
    extends:
      file: common.yml
      service: bioportal-4store
  bioportal-mgrep:
    extends:
      file: common.yml
      service: bioportal-mgrep
  bioportal-solr:
    extends:
      file: common.yml
      service: bioportal-solr
  redis-annotator:
    extends:
      file: common.yml
      service: redis-annotator
  redis-http:
    extends:
      file: common.yml
      service: redis-http
  redis-goo:
    extends:
      file: common.yml
      service: redis-goo
  bioportal-unitex:
    extends:
      file: common.yml
      service: bioportal-unitex
  bioportal-api:
    build: ./bioportal-api/
    container_name: bioportal-api
    volumes:
      - ./data/bioportal:/srv/bioportal/
      - ./data/ncbo_logs/:/srv/ncbo/ncbo_cron/logs/
      - ./data/mgrep/:/srv/mgrep/dictionary
      - ./data/unitex:/srv/unitex/
      - ./data/bioportal/reports:/srv/bioportal/reports/
      - ./data/var/run/:/var/run/
    ports:
      - "8080:8080"
      - "2222:22"
    depends_on:
      - redis-http
      - redis-goo
      - redis-annotator
      - bioportal-mgrep
      - bioportal-solr
      - bioportal-4store
      - bioportal-unitex
    links:
      - redis-http
      - redis-goo
      - redis-annotator
      - bioportal-mgrep
      - bioportal-solr
      - bioportal-4store
      - bioportal-unitex
  bioportal-annotator-proxy:
    build: ./bioportal-annotator-proxy/
    container_name: bioportal-annotator-proxy
    ports:
      - "8081:8081"
    depends_on:
      - bioportal-api
    links:
      - bioportal-api
